---
resources:
- name: pipelines-source
  type: git
  icon: github
  source:
    uri: https://github.com/rbogle/test-concourse-pipelines
    branch: main

jobs:
- name: set-self
  public: true
  plan:
  - get: pipelines-source
    trigger: true
  - set_pipeline: self
    file: pipelines-source/main-pipeline.yaml

- name: build-tooling-stack-pipelines
  public: true
  plan:
  - get: pipelines-source
    trigger: true
    passed: [set-self]
  - set_pipeline: tooling-stacks-controller
    file: pipelines-source/tooling-stack/tooling-stack-controller.yaml
    var_files:
      - pipelines-source/tooling-stack/tooling-stack-controller-vars.yaml