---
resources:
- name: pipelines-source
  type: git
  icon: github
  source:
    uri: https://github.com/rbogle/test-concourse-pipelines
    branch: main

- name: pipeline-lock
  type: pool
  source:
    uri: git@github.com:rbogle/concourse-locks.git
    branch: main
    pool: controller
    private_key: ((git_key))

jobs:
- name: lock-pipeline
  plan:
  - get: pipelines-source
    trigger: true
  - put: pipeline-lock
    params: {claim: main-pipeline}

- name: set-self
  plan:
  - get: pipelines-source
    trigger: true
    passed: [lock-pipeline]
  - set_pipeline: self
    file: pipelines-source/main-pipeline.yaml
    vars: 
      git_key: ((git_key))

- name: build-environment-controller
  plan:
  - get: pipelines-source
    trigger: true
    passed: [set-self]
  - set_pipeline: environment-pipeline-builder
    file: pipelines-source/environments/env-controller.yaml
    var_files:
      - pipelines-source/environments/env-controller-vars.yaml
  - put: pipeline-lock
    params: {release: main-pipeline}