---
resources:
- name: pipelines-source
  type: git
  icon: github
  source:
    uri: https://github.com/rbogle/test-concourse-pipelines
    branch: main

jobs:
- name: set-self
  public: true
  plan:
  - get: pipelines-source
    trigger: true
  - set_pipeline: self
    file: pipelines-source/main-pipeline.yaml

- name: build-environment-controller
  public: true
  plan:
  - get: pipelines-source
    trigger: true
    passed: [set-self]
  - set_pipeline: environment-pipeline-builder
    file: pipelines-source/environments/env-controller.yaml
    var_files:
      - pipelines-source/environments/env-controller-vars.yaml