---
jobs:
- name: set-lock
  plan:
    # Trigger here
  - get: ((environment.name))-source
  - put: env-pipeline-lock
    resource: pipeline-locks
    params: {claim: env-pipeline}

# do env compoent jobs

- name: ((environment.name))-task
  plan:
  - get: ((environment.name))-source
    passed: [set-lock]
  - task: first-task-((environment.name))
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: { repository: busybox }
      run:
        path: echo
        args: ["Hello, from ((environment.name)). The pipeline I was created by ((created_by))!"]


# gather and push versions
- name: set-versions
  plan:
   - get: 

- name: release-lock
  plan:
  - get: ((environment.name))-source
    passed: [set-versions]
  - put: pipeline-locks
    params: {release: env-pipeline-lock}


resources:
- name: pipeline-locks
  type: pool
  source:
    uri: git@github.com:rbogle/concourse-locks.git
    branch: main
    pool: ((environment.name))
    private_key: ((git_key))

- name: ((environment.name))-source
  type: git
  icon: github
  source:
    uri: ((environment.source_repo))
    branch: ((environment.source_branch))