---
resources:
- name: pipelines-source
  type: git
  icon: github
  source:
    uri: ((source_repo))
    branch: ((source_branch))

- name: pipeline-locks
  type: pool
  source:
    uri: ((locks_repo))
    branch: ((locks_branch))
    pool: ((locks_pool))
    private_key: ((git_key)) #ssh key

jobs:
- name: lock-pipeline
  plan:
  - get: pipelines-source
    trigger: true
  - put: pipeline-locks
    params: {claim: main-pipeline}

- name: set-self
  plan:
  - get: pipelines-source
    trigger: true
    passed: [lock-pipeline]
  - set_pipeline: self
    file: pipelines-source/pipeline-deployer/pipeline.yml
    var_files:
      - pipelines-source/pipeline-deployer/config.yml
    vars: 
      git_key: ((git_key))

- name: build-deployment-controller
  plan:
  - get: pipeline-locks
  - get: pipelines-source
    trigger: true
    passed: [set-self]
  - set_pipeline: deployment-controller
    file: pipelines-source/deployment-controller/controller-pipeline.yml
    var_files:
      - pipelines-source/deployment-controller/controller-vars.yml
    vars: 
      git_key: ((git_key))
      source_repo: ((source_repo))
      source_branch: ((source_branch))

- name: release-lock
  plan: 
  - get: pipelines-source
    trigger: true
    passed: [build-deployment-controller]
  - put: pipeline-locks
    params: {release: pipeline-locks}