---
resources:
- name: pipelines-source
  type: git
  icon: github
  source:
    uri: https://github.com/rbogle/test-concourse-pipelines
    branch: main

jobs:
- name: build-platform-pipelines
  plan:
  - get: pipelines-source
    trigger: true
  - load_var: config
    file: pipelines-source/deployments/platform/manifest.yml
  - across:
    - var: env
      values: ((.:config.environments))
    do:
     # we can add a task for pipeline file building 
     - set_pipeline: platform-((.:env.name))-deployment-pipeline
       file: pipelines-source/deployments/platform/pipeline-template.yaml
       vars-files:
        - pipelines-source/deployments/platform/((.env:name))/versions.yml
       vars: 
          environment: ((.:env)) # pass a whole json object
          # state_file: ((.:env.name))-state-file.yml
          created_by: ((source)) # injected by the main-pipeline at set-pipeline
          git_key: ((git_key))