---
platform: linux

image_resource:
  type: registry-image
  source: {repository: rbogle/concourse-fly}

inputs: 
 - name: pipelines_source
 - name: metadata

outputs:
 - name: versions

# params:
#  CONCOURSE_TARGET: 
#  CONCOURSE_URL: 
#  CONCOURSE_USER: 
#  CONCOURSE_PASSWD:

run:
  path: pipelines_source/deployments/platform/tasks/get-versions.sh 
